---
deployment:
  tasks:
    - export REACT_APP_API_URL=https://saddlebrown-armadillo-164855.hostingersite.com/api
    - export REACT_APP_APP_NAME=GestSocial
    - export REACT_APP_ENV=production
    - export CI=false
    - cd $HOME/repositories/App_gestion_servicios_sociales/frontend && npm install && npm run build
    - cp -r $HOME/repositories/App_gestion_servicios_sociales/frontend/build/. $HOME/public_html/
