-- Migración v001: Rollback
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS migraciones_bd;
DROP TABLE IF EXISTS notificaciones;
DROP TABLE IF EXISTS pagos;
DROP TABLE IF EXISTS cuotas;
DROP TABLE IF EXISTS miembros_grupo;
DROP TABLE IF EXISTS grupos_familiares;
DROP TABLE IF EXISTS planes;
DROP TABLE IF EXISTS afiliados;
DROP TABLE IF EXISTS usuarios;
SET FOREIGN_KEY_CHECKS = 1;
